#pragma once

/* Generated by asset converters. */

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(LV_LVGL_H_INCLUDE_SYSTEM)
#include <lvgl.h>
#else
#include "lvgl/lvgl.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
LV_IMAGE_DECLARE(image_cursor_hover);
LV_IMAGE_DECLARE(image_cursor_pressed);
LV_IMAGE_DECLARE(image_hud);
LV_IMAGE_DECLARE(image_icon_audio);
LV_IMAGE_DECLARE(image_icon_copy);
LV_IMAGE_DECLARE(image_icon_cut);
LV_IMAGE_DECLARE(image_icon_default);
LV_IMAGE_DECLARE(image_icon_delete);
LV_IMAGE_DECLARE(image_icon_folder);
LV_IMAGE_DECLARE(image_icon_fullscreen);
LV_IMAGE_DECLARE(image_icon_image);
LV_IMAGE_DECLARE(image_icon_info);
LV_IMAGE_DECLARE(image_icon_paste);
LV_IMAGE_DECLARE(image_icon_playback_1x);
LV_IMAGE_DECLARE(image_icon_playback_2x);
LV_IMAGE_DECLARE(image_icon_playback_5x);
LV_IMAGE_DECLARE(image_icon_playback_forward);
LV_IMAGE_DECLARE(image_icon_playback_pause);
LV_IMAGE_DECLARE(image_icon_playback_play);
LV_IMAGE_DECLARE(image_icon_playback_replay);
LV_IMAGE_DECLARE(image_icon_rename);
LV_IMAGE_DECLARE(image_icon_reset);
LV_IMAGE_DECLARE(image_icon_scripts);
LV_IMAGE_DECLARE(image_icon_text);
LV_IMAGE_DECLARE(image_icon_video);
LV_IMAGE_DECLARE(image_icon_zoom_in);
LV_IMAGE_DECLARE(image_icon_zoom_out);
LV_IMAGE_DECLARE(image_magic);
LV_IMAGE_DECLARE(image_magic_bow);
LV_IMAGE_DECLARE(image_magic_brick);
LV_IMAGE_DECLARE(image_magic_target);

/* Fonts */
LV_FONT_DECLARE(font_noto_sans_mono_semibold_12);
LV_FONT_DECLARE(font_noto_sans_mono_semibold_14);
LV_FONT_DECLARE(font_noto_sans_sc_semibold_10);
LV_FONT_DECLARE(font_noto_sans_sc_semibold_12);
LV_FONT_DECLARE(font_noto_sans_sc_semibold_14);
LV_FONT_DECLARE(font_noto_sans_jp_semibold_10);
LV_FONT_DECLARE(font_noto_sans_jp_semibold_12);
LV_FONT_DECLARE(font_noto_sans_jp_semibold_14);

#ifdef __cplusplus
}
#endif
